**bold text**

**Bag o Words**

In [77]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import re
import nltk
from nltk.corpus import stopwords
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [29]:
data = {
    "review": [
        "I absolutely love this phone! The camera quality is fantastic and battery lasts all day.",
        "Terrible experience. The screen broke within a week, and customer service was useless.",
        "Great value for money. Performance is smooth and build quality feels premium.",
        "The laptop overheats and the battery drains too fast. Very disappointed.",
        "Excellent sound quality and very comfortable to wear. Highly recommend these headphones!",
        "Worst product I’ve ever bought. It stopped working after two days.",
        "Amazing performance and display. Totally worth the price.",
        "Poor design and fragile build. I regret buying this item.",
        "Fast delivery and great packaging. The product works as expected.",
        "Customer support was unhelpful. Will not buy from this brand again."
    ],
    "sentiment": [
        "positive", "negative", "positive", "negative", "positive",
        "negative", "positive", "negative", "positive", "negative"
    ]
}

In [30]:
df=pd.DataFrame(data)
df.head()

                                              review sentiment
0  I absolutely love this phone! The camera quali...  positive
1  Terrible experience. The screen broke within a...  negative
2  Great value for money. Performance is smooth a...  positive
3  The laptop overheats and the battery drains to...  negative
4  Excellent sound quality and very comfortable t...  positive

In [31]:
def clean_text(text):
    text=text.lower()
    text=re.sub(r'[^a-zA-Z0-9\s]','',text)
    text=' '.join([word for word in text.split() if word not in stopwords.words('english')])
    return text

In [32]:
df['clean_review']=df['review'].apply(clean_text)
df

,review,sentiment,clean_review
0,I absolutely love this phone! The camera quali...,positive,absolutely love phone camera quality fantastic...
1,Terrible experience. The screen broke within a...,negative,terrible experience screen broke within week c...
2,Great value for money. Performance is smooth a...,positive,great value money performance smooth build qua...
3,The laptop overheats and the battery drains to...,negative,laptop overheats battery drains fast disappointed
4,Excellent sound quality and very comfortable t...,positive,excellent sound quality comfortable wear highl...
5,Worst product I’ve ever bought. It stopped wor...,negative,worst product ive ever bought stopped working ...
6,Amazing performance and display. Totally worth...,positive,amazing performance display totally worth price
7,Poor design and fragile build. I regret buying...,negative,poor design fragile build regret buying item
8,Fast delivery and great packaging. The product...,positive,fast delivery great packaging product works ex...
9,Customer support was unhelpful. Will not buy f...,negative,customer support unhelpful buy brand

In [33]:
cv=CountVectorizer(max_features=20)
X=cv.fit_transform(df['clean_review']).toarray()
y=df['sentiment']
print('Top 25 Words in Features X')
cv.get_feature_names_out()
bow_df=pd.DataFrame(X,columns=cv.get_feature_names_out())
bow_df

Top 25 Words in Features X

,amazing,battery,bought,brand,build,buy,buying,camera,comfortable,customer,day,delivery,design,disappointed,display,fast,great,performance,product,quality
0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1
3,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
5,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
7,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0
9,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [35]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [40]:
# User prediction
# Taking review dfrom user
print('\nEnter your review below : \n')
user_review = input('Enter your product review : ')

# clean the review
user_review=clean_text(user_review)
user_review_bow=cv.transform([user_review]).toarray()

# predict using model
user_sentiment=model.predict(user_review_bow)


# output predicted Sentiment
print('\n Cleaned Review',user_review)
print('\n Predicted Sentiment : ',user_sentiment[0])

Enter your review below :

Enter your product review : i hate this product, bad customer service

 Cleaned Review hate product bad customer service

 Predicted Sentiment :  negative

**Practice Exercise One**


input_text='Natural Langauage Processing is going to help you out in near future. You have to remember this!!! For getting interview calls'



**Do the following tasks:**

1. Splits text into words/tokens (show individual word token)
2. Clean Tokens (show clean token)
3. Remove Stop Words (Show token after removing stop words)
4. Stemming (Show the words in their root forms)
5. Lemmatizing (Show lemma words)

In [45]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [54]:
input_text = 'Natural Langauage Processing is going to help you out in near future. You have to remember this!!! For getting interview calls'

In [76]:
# Splits text into words/tokens (show individual word token)
tokens = word_tokenize(input_text)
tokens

['Natural',
 'Langauage',
 'Processing',
 'is',
 'going',
 'to',
 'help',
 'you',
 'out',
 'in',
 'near',
 'future',
 '.',
 'You',
 'have',
 'to',
 'remember',
 'this',
 '!',
 '!',
 '!',
 'For',
 'getting',
 'interview',
 'calls']

In [67]:
#Clean tokens( show clean token)
clean_tokens=[re.sub(r'[^a-zA-Z0-9]','',token.lower()) for token in tokens if token.isalpha()]
clean_tokens

['natural',
 'langauage',
 'processing',
 'is',
 'going',
 'to',
 'help',
 'you',
 'out',
 'in',
 'near',
 'future',
 'you',
 'have',
 'to',
 'remember',
 'this',
 'for',
 'getting',
 'interview',
 'calls']

In [71]:
#Remove Stop Words (Show token after removing stop words)
stop_words = set(stopwords.words('english'))

filtered_tokens = [token for token in clean_tokens if token not in stop_words]
print('token after removing stop words:')
filtered_tokens

token after removing stop words:

['natural',
 'langauage',
 'processing',
 'going',
 'help',
 'near',
 'future',
 'remember',
 'getting',
 'interview',
 'calls']

In [74]:
# Stemming (Show the words in their root forms)
stemmer = PorterStemmer()
stemmed_tokens = [stemmer.stem(word) for word in filtered_tokens]
print('The Tokens in their roots forms')
stemmed_tokens

The Tokens in their roots forms

['natur',
 'langauag',
 'process',
 'go',
 'help',
 'near',
 'futur',
 'rememb',
 'get',
 'interview',
 'call']

In [62]:
lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens_without_stopwords]
print(lemmatized_tokens)

['natural', 'langauage', 'processing', 'going', 'help', 'near', 'future', 'remember', 'getting', 'interview', 'call']

In [75]:
# Lemmatizing (Show lemma words)
lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]
print('Lemma Words')
lemmatized_tokens

Lemma Words

['natural',
 'langauage',
 'processing',
 'going',
 'help',
 'near',
 'future',
 'remember',
 'getting',
 'interview',
 'call']

In [81]:
#

In [80]:
# tfidf(Term Frequency-Inverse Document Frequency)
tfidf=TfidfVectorizer()
matrix=tfidf.fit_transform(lemmatized_tokens)
matrix
df=pd.DataFrame(matrix.toarray(),columns=tfidf.get_feature_names_out())
df

,call,future,getting,going,help,interview,langauage,natural,near,processing,remember
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [82]:
#

**TF-IDF Example 2**

In [83]:
corpus=['Pyhton developer required with strong coding skill',
        'Experience in REST API, Automation, Jenkins, Flask and Python',
        'looking for machine learning engineer familiar with NLP, Supervised, Unsupervised and Deep Learning'

]

In [84]:
tfidf=TfidfVectorizer()

matrix=tfidf.fit_transform(corpus)

df=pd.DataFrame(matrix.toarray(),columns=tfidf.get_feature_names_out())
df

,and,api,automation,coding,deep,developer,engineer,experience,familiar,flask,...,nlp,pyhton,python,required,rest,skill,strong,supervised,unsupervised,with
0,0.000000,0.000000,0.000000,0.389888,0.000000,0.389888,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.389888,0.000000,0.389888,0.000000,0.389888,0.389888,0.000000,0.000000,0.29652
1,0.259663,0.341426,0.341426,0.000000,0.000000,0.000000,0.000000,0.341426,0.000000,0.341426,...,0.000000,0.000000,0.341426,0.000000,0.341426,0.000000,0.000000,0.000000,0.000000,0.00000
2,0.202130,0.000000,0.000000,0.000000,0.265777,0.000000,0.265777,0.000000,0.265777,0.000000,...,0.265777,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.265777,0.265777,0.20213

In [87]:
print('\n Top weighted terms')
print(df.mean().sort_values(ascending=False).head(10))

 Top weighted terms
learning     0.177185
with         0.166217
and          0.153931
required     0.129963
developer    0.129963
skill        0.129963
pyhton       0.129963
coding       0.129963
strong       0.129963
api          0.113809
dtype: float64